name: qaltrix
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  supabase_flutter: ^2.0.0
  path_provider: ^2.0.15
  http: ^1.3.6
  telephony:
    git:
      url: https://github.com/shounakmulay/telephony.git
  geolocator: ^14.0.2
  permission_handler: ^11.2.0
  url_launcher: ^6.1.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
     android: true
     ios: true
     image_path: "assets/logo.jpg"



flutter:
  uses-material-design: true
  assets:
    - assets/Qaltrix.jpg
    - assets/jeral.jpg
    - assets/unni.jpg
    - assets/joyan.jpg
    - assets/emmanuel.jpg
    - assets/splash.png